services:
  backend:
    build: ./backend
    depends_on:
      - database
      - elasticsearch-service
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    networks:
      - chatnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      SECRET_KEY: supersecret
      ALGORITHM: HS256
      ES_SERVICE_URL: "http://elasticsearch-service:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BROWSER=none
      - REACT_APP_SOCKET_SERVER_URL=http://backend:4000
      - REACT_APP_API_URL=http://backend:4000
    stdin_open: true
    tty: true
    networks:
      - chatnet

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatnet

  elastic-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elastic-node
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - chatnet

  elasticsearch-service:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch-service
    ports:
      - "8000:8000"
    depends_on:
      - elastic-node
    networks:
      - chatnet
    environment:
      - ES_HOST=http://elastic-node:9200


networks:
  chatnet:
    driver: bridge

volumes:
  db_data:
  esdata:
