version: "3.8"

services:
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    networks:
      - chatnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      SECRET_KEY: supersecret
      ALGORITHM: HS256
      ES_HOST: http://elasticsearch:9200

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BROWSER=none
      - REACT_APP_SOCKET_SERVER_URL=http://backend:4000      
    stdin_open: true
    tty: true
    networks:
      - chatnet

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatnet

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge

volumes:
  db_data:
  esdata:
